##
# This file contains Values.yaml content that gets added to the output of questions.yaml
# It's ONLY meant for content that the user is NOT expected to change.
# Example: Everything under "image" is not included in questions.yaml but is included here.
##

image:
  repository: bitnami/postgresql
  pullPolicy: IfNotPresent
  tag: 13.4.0@sha256:0fa00d56daee4ab334e0b5aeabfb8674aadc501e498ca13feac5b5fdced4bcba


initContainers:
  migrate-db:
    image: "{{ .Values.alpineImage.repository}}:{{ .Values.alpineImage.tag }}"
    securityContext:
      runAsUser: 0
      privileged: true
      allowPrivilegeEscalation: true
      runAsNonRoot: false
    command:
      - /bin/sh
      - -cx
      - |
        echo 'trying to migrate old db to new location...'
        chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /bitnami/postgresql/data /bitnami/postgresql/old
        chmod 775 /bitnami/postgresql/data/ bitnami/postgresql/data /bitnami/postgresql/old
        mkdir -p /bitnami/postgresql/data
        mkdir -p /bitnami/postgresql/conf
        mv -f /bitnami/postgresql/old/* /bitnami/postgresql/data/ || true
        mv -f /bitnami/postgresql/data/pg_hba.conf /bitnami/postgresql/conf/pg_hba.conf || true
        chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /bitnami/postgresql/data
        chmod 775 /bitnami/postgresql/data
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: db
        mountPath: /bitnami/postgresql/old
      - name: data
        mountPath: /bitnami/postgresql

envValueFrom:
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: '{{ .Values.existingSecret | default ( include "common.names.fullname" . ) }}'
      key: "postgresql-password"

envTpl:
  POSTGRES_USER: "{{ .Values.postgresqlUsername }}"
  POSTGRES_DB: "{{ .Values.postgresqlDatabase }}"
#  POSTGRESQL_POSTGRES_PASSWORD: "{{ .Values.postgrespassword }}"
#  POSTGRESQL_PASSWORD: "{{ .Values.password }}"

##
# Most other defaults are set in questions.yaml
# For other options please refer to the wiki, default_values.yaml or the common library chart
##
