apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 7.0.12
deprecated: false
description: Get all your books, like series with Sonarr...
home: https://github.com/truecharts/apps/tree/master/charts/incubator/lazylibrarian
icon: https://lazylibrarian.gitlab.io/logo.svg
keywords:
- lazylibrarian
- ebooks
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
- email: kjeld@schouten-lebbing.nl
  name: Ornias1993
  url: truecharts.org
name: lazylibrarian
sources:
- https://gitlab.com/LazyLibrarian/LazyLibrarian.git
- https://lazylibrarian.gitlab.io
type: application
version: 7.0.2
