# Default values for LazyLibrarian.

image:
  repository: ghcr.io/linuxserver/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:65ff3e1b07097396c5c03e4e59d78df9b07979556740d7e7e2568009077bebe3

service:
  main:
    ports:
      main:
        port: 5299

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
