apiVersion: v2
appVersion: 5.2.0
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 7.0.12
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 2.2.0
- condition: memcached.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 5.14.2
deprecated: false
description: Groupware package
home: https://github.com/truecharts/apps/tree/master/charts/stable/sogo
icon: https://truecharts.org/_static/img/sogo-icon.png
keywords:
- groupware
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
name: sogo
sources:
- https://www.sogo.nu/
type: application
version: 3.0.2
