# Default values for Bitwarden.
image:
  repository: ghcr.io/truecharts/sogo
  pullPolicy: IfNotPresent
  tag: v5.2.0@sha256:8fc7bb87b77d76d929bcd36403d4f27878fa3e99f5448fb05ed64829078665a4

postgresqlImage:
  repository: bitnami/postgresql
  pullPolicy: IfNotPresent
  tag: 13.4.0@sha256:0fa00d56daee4ab334e0b5aeabfb8674aadc501e498ca13feac5b5fdced4bcba

# -- services
service:
  main:
    ports:
      main:
        port: 80

# -- initcontainers
initContainers:
  # -- wait for database before starting sogo
  init-postgresdb:
    image: "{{ .Values.postgresqlImage.repository }}:{{ .Values.postgresqlImage.tag }}"
    command:
      - "sh"
      - "-c"
      - "until pg_isready -U sogo -h ${pghost} ; do sleep 2 ; done"
    imagePullPolicy: IfNotPresent
    env:
      - name: pghost
        valueFrom:
          secretKeyRef:
            name: dbcreds
            key: plainhost

# -- persistence settings
persistence:
  data:
    enabled: true
    mountPath: "/data/conf/sogo/"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
  drafts:
    enabled: true
    mountPath: "/var/spool/sogo"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
  mimetmp:
    enabled: true
    mountPath: "/mimetmp"
    type: emptyDir


# -- postgres dependency settings
postgresql:
  enabled: true
  postgresqlUsername: sogo
  postgresqlDatabase: sogo
  existingSecret: dbcreds

# --  memcached dependency settings
memcached:
  enabled: true

# -- Sogo settings
sogo:
  # -- Pre-configured Sogo mail settings
  mail:
    SOGoDraftsFolderName: "Drafts"
    SOGoSentFolderName: "Sent"
    SOGoTrashFolderName: "Trash"
    SOGoIMAPServer: "localhost"
    SOGoSieveServer: ""
    SOGoMailDomain: "example.com"
    SOGoMailingMechanism: "smtp"
    SOGoSMTPServer: "smtp://domain:port"
    SOGoForceExternalLoginWithEmail: false
    SOGoMailSpoolPath: "/var/spool/sogo"
    NGMimeBuildMimeTempDirectory: "/mimetmp"
  # -- Pre-configured Sogo notifications settings
  notifications:
    SOGoAppointmentSendEMailNotifications: false
    SOGoACLsSendEMailNotifications: false
    SOGoFoldersSendEMailNotifications: false
  # -- Pre-configured general Sogo settings
  general:
    SOGoLanguage: "English"
    SOGoSuperUsernames: ""
    SxVMemLimit: "384"
  # -- Pre-configured Sogo authentication settings
  auth:
    SOGoPasswordChangeEnabled: true
  # -- Sogo usersources
  usersources: []
  #  - type: "ldap"
  #    CNFieldName: "cn"
  #    UIDFieldName: "uid"
  #    IDFieldName: "uid"
  #    bindFields: "(uid, mail)"
  #    baseDN: "ou=users,dc=acme,dc=com"
  #    bindDN: "uid=sogo,ou=users,dc=acme,dc=com"
  #    bindPassword: "qwerty"
  #    canAuthenticate: true
  #    displayName: "Shared Addresses"
  #    hostname: "ldap://127.0.0.1:389"
  #    id: "public"
  #    isAddressBook: true
  #    custom:
  #      - name: name-of-ldap-setting
  #        value: somevalue
  #
  #  - type: "sql"
  #    id: "directory"
  #    viewURL: "postgresql://sogo:sogo@127.0.0.1:5432/sogo/sogo_view"
  #    canAuthenticate: true
  #    isAddressBook: true
  #    userPasswordAlgorithm: "md5"
  #    custom:
  #      - name: name-of-sql-setting
  #        value: somevalue

  # -- Pre-configured Sogo debug settings
  debug:
    SOGoDebugRequests: false
    SoDebugBaseURL: false
    LDAPDebugEnabled: false
    ImapDebugEnabled: false
    PGDebugEnabled: false
    MySQL4DebugEnabled: false
    SOGoUIxDebugEnabled: false
    WODontZipResponse: false
    WOLogFile: "/var/log/sogo/sogo.log"
  # -- Pre-configured Sogo webui settings
  webui:
    SOGoPageTitle: "SOGo"
    SOGoVacationEnabled: true
    SOGoForwardEnabled: true
    SOGoSieveScriptsEnabled: true
    SOGoMailAuxiliaryUserAccountsEnabled: true
    SOGoTrustProxyAuthentication: false
    SOGoXSRFValidationEnabled: true
  # -- custom Sogo setting arguments
  custom: []
  # - name: SOGoPageTitle
  #   value: "somevalue"
