apiVersion: v2
appVersion: 1.22.2
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 7.0.12
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 2.2.0
deprecated: false
description: Unofficial Bitwarden compatible server written in Rust
home: https://github.com/truecharts/apps/tree/master/charts/stable/vaultwarden
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/256x256.png
keywords:
- bitwarden
- bitwardenrs
- bitwarden_rs
- vaultwarden
- password
- rust
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
- email: kjeld@schouten-lebbing.nl
  name: Ornias1993
  url: truecharts.org
name: vaultwarden
sources:
- https://github.com/dani-garcia/vaultwarden
type: application
version: 8.0.2
