apiVersion: v2
appVersion: 4.30.4
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 7.0.12
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 2.2.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.3.2
deprecated: false
description: Authelia is a Single Sign-On Multi-Factor portal for web apps
home: https://github.com/truecharts/apps/tree/master/charts/stable/authelia
icon: https://avatars2.githubusercontent.com/u/59122411?s=200&v=4
keywords:
- authelia
- authentication
- login
- SSO
- Authentication
- Security
- Two-Factor
- U2F
- YubiKey
- Push Notifications
- LDAP
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
name: authelia
sources:
- https://github.com/authelia/chartrepo
- https://github.com/authelia/authelia
type: application
version: 3.0.3
