apiVersion: v2
appVersion: 5.5.12
dependencies:
- name: common
  repository: https://truecharts.org/
  version: 7.0.12
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 2.2.0
deprecated: false
description: A free and open source personal finance manager
home: https://github.com/firefly-iii/firefly-iii/
icon: https://www.firefly-iii.org/assets/logo/color.png
keywords:
- fireflyiii
- finacial
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: truecharts.org
- email: 20650065+warllo54@users.noreply.github.com
  name: warllo54
  url: truecharts.org
name: fireflyiii
sources:
- https://github.com/firefly-iii/firefly-iii/
type: application
version: 8.0.2
